### ISSUE TITLE
Fix "ArgumentOutOfRangeException" on InventoryItem DragDrop

### ISSUE THREAD

**Issue by OWeinert** [Piggo41/PnP-Organizer#10]
Sometimes when an Inventory Item is dragged and dropped onto another Item it will throw an "ArgumentOutOfRangeException" on the following line:

https://github.com/Piggo41/PnP-Organizer/blob/dce33e42116fae0abe9611659da4e78803e3fefe/PnP%20Organizer/Views/Pages/InventoryPage.xaml.cs#L176

**Comment by Piggo41** [comment]
fixed
